CHANNELS = [
    # ── Saudi Arabia ──────────────────────────────────────────────
    {"name": "Rotana Music",          "handle": "rotanamusic",          "country": "SA", "category": "Music"},
    {"name": "mmoshaya",              "handle": "mmoshaya",             "country": "SA", "category": "Entertainment"},
    {"name": "BanderitaX",            "handle": "banderitax",           "country": "SA", "category": "Gaming"},
    {"name": "AboFlah",               "handle": "aboflah",              "country": "SA", "category": "Entertainment"},
    {"name": "Katakit Baby TV",       "handle": "katakit_baby",         "country": "SA", "category": "Kids"},
    {"name": "Mohamad Adnan",         "handle": "mohamadadnan",         "country": "SA", "category": "Football"},
    {"name": "Al Arabiya",            "handle": "alarabiya",            "country": "SA", "category": "News"},
    {"name": "Bader Al-Shalawi",      "handle": "badershalawiofficial", "country": "SA", "category": "Comedy"},
    {"name": "Fares Matar",           "handle": "faresmatar",           "country": "SA", "category": "Tech"},
    {"name": "Anas Marwah",           "handle": "anasmarwah",           "country": "SA", "category": "Vlogs"},
    {"name": "Telfaz11",              "handle": "telfaz11",             "country": "SA", "category": "Comedy"},
    {"name": "Hussain Al Jassmi",     "handle": "hussainjassmi",        "country": "SA", "category": "Music"},
    {"name": "Haifa Wehbe",           "handle": "haifawehbe",           "country": "SA", "category": "Music"},
    {"name": "Aseel Abou Bakr",       "handle": "aseelabubakr",         "country": "SA", "category": "Music"},
    {"name": "MBC Masr",              "handle": "mbcmasr",              "country": "SA", "category": "TV"},
    {"name": "Arab Idol",             "handle": "arabidol",             "country": "SA", "category": "Entertainment"},
    {"name": "Rotana Khalijiah",      "handle": "rotanakhalijiah",      "country": "SA", "category": "Music"},
    {"name": "Rotana Classic",        "handle": "rotanaclassic",        "country": "SA", "category": "Music"},
    {"name": "Abdul Majeed Abdullah", "handle": "abdulmajeedabdullah",  "country": "SA", "category": "Music"},
    {"name": "Mohammed Abdo",         "handle": "mohammedabdo",         "country": "SA", "category": "Music"},

    # ── Egypt ──────────────────────────────────────────────────────
    {"name": "Diana and Roma ARA",    "handle": "dianaromaara",         "country": "EG", "category": "Kids"},
    {"name": "Noor Stars",            "handle": "noorstars",            "country": "EG", "category": "Lifestyle"},
    {"name": "Osratouna TV",          "handle": "osratouna",            "country": "EG", "category": "Kids"},
    {"name": "Joe HaTTab",            "handle": "joehattab",            "country": "EG", "category": "Entertainment"},
    {"name": "Anas Elshayb",          "handle": "anasalshayeb",         "country": "EG", "category": "Comedy"},
    {"name": "King Misr",             "handle": "kingmisr",             "country": "EG", "category": "Entertainment"},
    {"name": "Adam Montaser",         "handle": "adammontaser",         "country": "EG", "category": "Comedy"},
    {"name": "Ahmed Sheba",           "handle": "ahmedsheba",           "country": "EG", "category": "Comedy"},
    {"name": "Bayoumi Funk",          "handle": "bayoumifunk",          "country": "EG", "category": "Comedy"},
    {"name": "Hamada Helal",          "handle": "hamadahelal",          "country": "EG", "category": "Music"},
    {"name": "Amr Diab",              "handle": "amrdiab",              "country": "EG", "category": "Music"},
    {"name": "Tamer Hosny",           "handle": "tamerhosny",           "country": "EG", "category": "Music"},
    {"name": "Mohamed Ramadan",       "handle": "mohamedramadanofficial","country": "EG", "category": "Music"},
    {"name": "CBC Egypt",             "handle": "cbcegypt",             "country": "EG", "category": "News"},
    {"name": "Oka and Ortega",        "handle": "okawortega",           "country": "EG", "category": "Music"},
    {"name": "Mostafa Hagag",         "handle": "mostafhagag",          "country": "EG", "category": "Gaming"},
    {"name": "Saad Lamjarred",        "handle": "saadlamjarred",        "country": "EG", "category": "Music"},
    {"name": "Ahmed Helmy",           "handle": "ahmedhelmy",           "country": "EG", "category": "Comedy"},
    {"name": "Zap Tharwat",           "handle": "zaptharwat",           "country": "EG", "category": "Music"},
    {"name": "Ahmed Fahmy",           "handle": "ahmedfahmy",           "country": "EG", "category": "Comedy"},

    # ── UAE / Pan-Arab ─────────────────────────────────────────────
    {"name": "Get Movies",            "handle": "getmovies",            "country": "AE", "category": "Kids"},
    {"name": "Shfa",                  "handle": "shfa",                 "country": "AE", "category": "Kids"},
    {"name": "Om Sayf",               "handle": "omsayf",               "country": "AE", "category": "Comedy"},
    {"name": "Majd Alzakout",         "handle": "majderzagout",         "country": "AE", "category": "Vlogs"},
    {"name": "Al Jazeera Arabic",     "handle": "aljazeeraarabic",      "country": "QA", "category": "News"},
    {"name": "BBC Arabic",            "handle": "bbcarabic",            "country": "AE", "category": "News"},
    {"name": "Sky News Arabia",       "handle": "skynewsarabia",        "country": "AE", "category": "News"},
    {"name": "France 24 Arabic",      "handle": "france24arabic",       "country": "AE", "category": "News"},
    {"name": "DW Arabic",             "handle": "dwarabic",             "country": "AE", "category": "News"},
    {"name": "RT Arabic",             "handle": "rtarabic",             "country": "AE", "category": "News"},
    {"name": "Euronews Arabic",       "handle": "euronewsarabic",       "country": "AE", "category": "News"},
    {"name": "Yanni Vadani",          "handle": "yannivadani",          "country": "AE", "category": "Vlogs"},

    # ── Jordan / Lebanon / Syria / Iraq / Palestine ────────────────
    {"name": "Sham Drama",            "handle": "shamdrama",            "country": "SY", "category": "Drama"},
    {"name": "Roya TV",               "handle": "royatv",               "country": "JO", "category": "News"},
    {"name": "LBC Group",             "handle": "lbcgroup",             "country": "LB", "category": "TV"},
    {"name": "LBCI Lebanon",          "handle": "lbcilebanon",          "country": "LB", "category": "News"},
    {"name": "MTV Lebanon",           "handle": "mtvlebanon",           "country": "LB", "category": "Entertainment"},
    {"name": "Anwar Osman",           "handle": "anwarosman",           "country": "SY", "category": "Comedy"},
    {"name": "Sama TV",               "handle": "samatv",               "country": "SY", "category": "TV"},
    {"name": "Al Mayadeen",           "handle": "almayadeen",           "country": "LB", "category": "News"},
    {"name": "Baghdad Today",         "handle": "baghdadtoday",         "country": "IQ", "category": "News"},
    {"name": "Dijlah TV",             "handle": "dijlahtv",             "country": "IQ", "category": "TV"},
    {"name": "Wissam Breidy",         "handle": "wissambreidy",         "country": "LB", "category": "Comedy"},
    {"name": "Bassem Youssef",        "handle": "bassemyoussef",        "country": "EG", "category": "Comedy"},

    # ── Morocco / Tunisia / Algeria ────────────────────────────────
    {"name": "Medi1 TV",              "handle": "medi1tv",              "country": "MA", "category": "News"},
    {"name": "2M Maroc",              "handle": "2mmaroc",              "country": "MA", "category": "TV"},
    {"name": "Nessma TV",             "handle": "nessmatv",             "country": "TN", "category": "TV"},
    {"name": "El Hiwar Ettounsi",     "handle": "elhiwarettounsi",      "country": "TN", "category": "TV"},
    {"name": "Ennahar TV",            "handle": "ennahartv",            "country": "DZ", "category": "News"},
    {"name": "Echorouk TV",           "handle": "echorouktvdz",         "country": "DZ", "category": "TV"},
    {"name": "Rachid Show",           "handle": "rachidshow",           "country": "DZ", "category": "Comedy"},

    # ── Sports (Pan-Arab) ──────────────────────────────────────────
    {"name": "Bein Sports Arabic",    "handle": "beinsportsarabic",     "country": "QA", "category": "Sports"},
    {"name": "Al Kass Sports",        "handle": "alkasssports",         "country": "QA", "category": "Sports"},
]